### ISSUE TITLE
插件连接非80端口gitlab时会连接默认80端口

### ISSUE THREAD

**Issue by xffan-xj** [TencentBlueKing/ci-checkout#20]
![QQ图片20210617173518](https://user-images.githubusercontent.com/63248061/122371702-a546fd80-cf92-11eb-8933-605689076f63.png)
![QQ图片20210617173523](https://user-images.githubusercontent.com/63248061/122371743-ad9f3880-cf92-11eb-9e3c-cf9f32e687b4.png)
插件版本使用的是1.0.4

**Comment by mingshewhe** [comment]
[v2.0.1](https://github.com/TencentBlueKing/ci-checkout/releases/tag/v2.0.1)以后已修复
