### ISSUE TITLE
在windows10构建机上无法启动ssh-agent服务

### ISSUE THREAD

**Issue by wenchao-h** [TencentBlueKing/ci-checkout#23]
插件在windows10构建机上无法启动ssh-agent服务，使用ssh私钥凭证拉取代码失败
![image](https://user-images.githubusercontent.com/33511440/126279145-389f39c8-99df-4b7e-bac0-962ee13caed2.png)
![image](https://user-images.githubusercontent.com/33511440/126279159-41259332-ea3a-4051-8ff1-33e23bcee663.png)
插件版本使用的是v1.0.5

**Comment by mingshewhe** [comment]
[v1.0.7](https://github.com/TencentBlueKing/ci-checkout/releases/tag/v1.0.7) 以后版本已修复
