### ISSUE TITLE
bug: Fail to get the credential because of null 

### ISSUE THREAD

**Issue by WCJ-Chance** [TencentBlueKing/ci-checkout#24]
![image](https://user-images.githubusercontent.com/78134833/159915315-f03b91e4-2f04-4ce1-a735-87b518682c33.png)
这个bug经常复现，尤其是在并发流水线的时候，有什么办法可以解决吗？

**Comment by mingshewhe** [comment]
这个是调用后台/ticket/api/build/credentials/{credentialId}接口失败了，需要查看后台ticket服务日志，默认在路径/data/bkce/logs/ci/ticket/ticket-devops.log路径下，方便看下是否有报错日志

**Comment by WCJ-Chance** [comment]
抱歉过了这么久···

**Comment by WCJ-Chance** [comment]
抱歉过了这么久，当初我发现是DHUtil生成randomKey的过程有缺陷，所以直接通过/ticket/api/build/credentials/$credentialId/detail这个接口去获取明文，就没有上面那个问题了。

**Comment by mingshewhe** [comment]
> 抱歉过了这么久，当初我发现是DHUtil生成randomKey的过程有缺陷，所以直接通过/ticket/api/build/credentials/$credentialId/detail这个接口去获取明文，就没有上面那个问题了。

抱歉，我也过了这么久，
> DHUtil生成randomKey的过程有缺陷，

这个缺陷是哪里有问题？因为我发现BouncyCastle如果版本不同会有不兼容的问题，偶现
> 直接通过/ticket/api/build/credentials/$credentialId/detail这个接口去获取明文

这个你是自己改了插件的实现吗？
